version: '3.7'

services:
  message-service:
    image: ${IMAGE}
    ports:
      - "8081:8080"
    networks:
      - default
      - dealog_dev
    links:
      - db
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - MP_MESSAGING_INCOMING_MESSAGES_AUTO_OFFSET_RESET=latest
      - QUARKUS_DATASOURCE_JDBC_URL=${QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=drop-and-create
      - QUARKUS_LOG_CONSOLE_JSON='false'
      - QUARKUS_LOG_LEVEL=DEBUG
      - QUARKUS_LOG_CONSOLE_LEVEL=DEBUG
  db:
    image: kartoza/postgis:latest
    ports:
      - 5432:5432
    networks:
      - default
      - dealog_dev

networks:
  dealog_dev:
    external: true