version: '3.7'

services:
  message-service:
    image: ${IMAGE}
    ports:
      - "8081:8080"
    networks:
      - default
      - dealog_dev
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - MP_MESSAGING_INCOMING_MESSAGES_AUTO_OFFSET_RESET=earliest
      - QUARKUS_DATASOURCE_JDBC_URL=${QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_LOG_CONSOLE_JSON='false'
      - QUARKUS_LOG_LEVEL=DEBUG
      - QUARKUS_LOG_CONSOLE_LEVEL=DEBUG
networks:
  dealog_dev:
    external: true

