name: Build Maven project, dockerize & publish

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project

    steps:
    - uses: actions/checkout@v2

    - name: Set version number
      id: version
      uses: DEalog/version-action@v0.1.0
      with:
        fallback-prefix: "1.0.0-SNAPSHOT-"

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
  
    - name: Setup GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0

    - name: Create settings.xml
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        repositories: '[{ "id": "github", "name": "dealog-common", "url": "https://maven.pkg.github.com/dealog/dealog-common" }]'
        servers: '[{"id": "github", "username": "${{ secrets.SERVER_USERNAME }}", "password": "${{ secrets.SERVER_PASSWORD }}"}]'

    - name: Build with Maven
      id: build
      run: |
        ./mvnw versions:set -DnewVersion=${{ steps.version.outputs.version_number }}
        ./mvnw package --file pom.xml --batch-mode --settings ~/.m2/settings.xml -Pnative
    
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: message-service
        path: |
          ./target/*-runner
          ./version.txt
          ./src/main/docker/Dockerfile.native

  publish:
    runs-on: ubuntu-latest
    name: Dockerize and publish
    needs: build

    steps:
    - name: Fetch artifact
      uses: actions/download-artifact@v2
      with:
        name: message-service

    - name: Set env
      run: |
        echo ::set-env name=VERSION::$(cat ./version.txt)
        echo ::set-env name=IMAGE_REPO::message-service
        echo ::set-env name=AWS_REGION::eu-central-1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      id: docker-build
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        image_name: ${{ env.IMAGE_REPO }}
        image_tag: ${{ env.VERSION }}
        registry: ${{ steps.login-ecr.outputs.registry }}
        dockerfile: ./src/main/docker/Dockerfile.native
    
    - name: Store docker image name
      run: echo ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }} >> ./full_image_name.txt
      shell: bash

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: dockerized-message-service
        path: |
          ./full_image_name.txt