# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        repositories: '[{ "id": "github", "name": "dealog-common", "url": "https://maven.pkg.github.com/dealog/dealog-common" }]'
        servers: '[{"id": "github", "username": "${secrets.SERVER_USERNAME}", "password": "${secrets.SERVER_PASSWORD}"}]'
    - name: Build with Maven
      run: ./mvnw package --file pom.xml --batch-mode --settings settings.xml -Pnative -Dquarkus.native.container-build=true -DprojectVersion=1.0.0-SNAPSHOT-${GITHUB_SHA::8}
